miriade_user_profil:
    path:     /mon-profil
    defaults: { _controller: MiriadeUserBundle:User:view }

miriade_user_profil_update:
    path:     /mon-profil/update
    defaults: { _controller: MiriadeUserBundle:User:update }