miriade_home:
    pattern: /
    defaults:
        _controller: MiriadeEventBundle:Default:home

miriade_event_dashboard:
    pattern: /event/dashboard
    defaults:
        _controller: MiriadeEventBundle:Event:dashboard

miriade_event_new:
    pattern: /event/new
    defaults:
        _controller: MiriadeEventBundle:Event:new

miriade_event_new_session:
    pattern: /event/new/session/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:newSession

miriade_event_new_partenaire:
    pattern: /event/new/partenaire/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:newPartenaire

miriade_event_show:
    pattern: /event/{slug}
    defaults:
        _controller: MiriadeEventBundle:Event:home
    requirements:
              slug:   ^[a-zA-Z0-9_-]+$

miriade_event_program:
    pattern: /event/program/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:program

miriade_event_contact:
    pattern: /event/contact/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:contact

miriade_event_about:
    pattern: /event/about/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:about

miriade_event_map:
    pattern: /event/map/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:map

miriade_event_participation:
    pattern: /event/{slug}/participation
    defaults: { _controller: MiriadeEventBundle:Event:participation }
    requirements:
        slug:   ^[a-zA-Z0-9_-]+$
