miriade_event_event_dashboard:
    pattern: /event/dashboard
    defaults:
        _controller: MiriadeEventBundle:Event:dashboard

miriade_event_event_new:
    pattern: /event/new
    defaults:
        _controller: MiriadeEventBundle:Event:new

miriade_event_event_create:
    pattern: /event/create
    defaults:
        _controller: MiriadeEventBundle:Event:create