miriade_event_dashboard:
    pattern: /event/dashboard
    defaults:
        _controller: MiriadeEventBundle:Event:dashboard
        
miriade_home:
    pattern: /{id}
    defaults:
        _controller: MiriadeEventBundle:Event:home
    requirements:
              id: \d+
        
miriade_event_new:
    pattern: /event/new
    defaults:
        _controller: MiriadeEventBundle:Event:new

miriade_event_new_session:
    pattern: /event/new/session/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:newSession

miriade_event_new_partenaire:
    pattern: /event/new/partenaire/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:newPartenaire

miriade_event_create:
    pattern: /event/create
    defaults:
        _controller: MiriadeEventBundle:Event:create

miriade_event_partner_new:
    pattern: /partner/new
    defaults:
        _controller: MiriadeEventBundle:Partner:new

miriade_event_partner_create:
    pattern: /partner/create
    defaults:
        _controller: MiriadeEventBundle:Partner:create

miriade_event_session_new:
    pattern: /session/new
    defaults:
        _controller: MiriadeEventBundle:Session:new

miriade_event_session_create:
    pattern: /session/create
    defaults:
        _controller: MiriadeEventBundle:Session:create
        
miriade_event_show:
    pattern: /event/show/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:show

miriade_event_program:
    pattern: /event/program/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:program

miriade_event_contact:
    pattern: /event/contact/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:contact
        
miriade_event_about:
    pattern: /event/about/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:about
        
miriade_event_map:
    pattern: /event/map/{id}
    defaults:
        _controller: MiriadeEventBundle:Event:map
